### ISSUE TITLE
int64 serialization doesn't match the one in ocaml atdgen-runtime

### ISSUE THREAD

**Issue by thatportugueseguy** [ahrefs/bs-atdgen-codec-runtime#22]
When we have a type with an ocaml representation of `int64`, it doesn't get serialized in the same way as it would in ocaml atdgen-runtime. 
ex: 
```ocaml
type int64 = int <ocaml repr="int64">
```
In this example, the value would be returned from the ocaml side as an `int` in the json response, and the atdgen-codec-runtime would complain that it can't parse that value as it's expecting a string.

### Int64 serialization functions:
ocaml atdgen-runtime:
```ocaml
let write_int64 ob x =
  Bi_outbuf.add_string ob (Int64.to_string x)
```

bs-atdgen-codec-runtime:
```ocaml
let int64 s = string (Int64.to_string s)
```

**Comment by Khady** [comment]
@zindel this is fixed now?

**Comment by jchavarri** [comment]
Not fixed. The patch was reverted in https://github.com/ahrefs/atd/pull/330.
